import {api} from './api.js?v=20260921-antigravity2';
import {getState,setState,setData} from './state.js?v=20260921-antigravity2';
import {today,currentMonth,esc,money,fmtDate,shortDate,weekday,norm,monthDays,monthWeeks,timeRange,subProgress,kpiProgress,portfolioProgress,kpiIsHealthy,pct,download} from './utils.js?v=20260921-antigravity2';

const $=s=>document.querySelector(s), S=()=>getState();
const titles={dashboard:'Dashboard',kpi:'KPI',planning:'Kế hoạch',payroll:'Lương & Chấm công',reports:'Báo cáo',backup:'Xuất dữ liệu',settings:'Cài đặt'};
let submitModal=null,busy=0;
const toast=(msg,error=false)=>{const el=document.createElement('div');el.className=`toast ${error?'error':''}`;el.textContent=msg;$('#toast').append(el);setTimeout(()=>el.remove(),3500)};
async function run(fn,msg){busy++;document.body.classList.add('busy');try{const r=await fn();if(msg)toast(msg);return r}catch(e){toast(e.message||String(e),true);throw e}finally{if(!--busy)document.body.classList.remove('busy')}}
async function refresh(){setData(await run(()=>api.load(S().period)));render()}
const input=(n,l,v='',type='text',extra='')=>`<label><span>${esc(l)}</span><input name="${n}" type="${type}" value="${esc(v??'')}" ${extra}></label>`;
const area=(n,l,v='')=>`<label class="full"><span>${esc(l)}</span><textarea name="${n}">${esc(v??'')}</textarea></label>`;
const select=(n,l,v,opts,extra='')=>`<label><span>${esc(l)}</span><select name="${n}" ${extra}>${opts.map(([x,t])=>`<option value="${esc(x)}" ${String(x)===String(v)?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
function modal(title,body,onSubmit,{wide=false,danger=false,save='Lưu',className='',hideFooter=false}={}){submitModal=onSubmit;$('#overlay').hidden=false;$('#overlay').innerHTML=`<div class="modal ${wide?'wide':''} ${className}" role="dialog" aria-modal="true"><header><div><small>FLOW KPI</small><h2>${esc(title)}</h2></div><button data-close aria-label="Đóng"><span class="svg-icon" style="--icon: url('./assets/icons/close.svg')"></span></button></header><form id="modalForm"><div class="modal-body">${body}</div>${hideFooter?'':`<footer><button type="button" class="btn ghost" data-close>Hủy</button><button class="btn ${danger?'danger':'primary'}">${esc(save)}</button></footer>`}</form></div>`;$('#modalForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,v=Object.fromEntries(new FormData(f));f.querySelectorAll('[type=checkbox]').forEach(x=>v[x.name]=x.checked);const ok=await submitModal(v,f);if(ok!==false)closeModal()};$('#overlay').querySelector('input,select,textarea')?.focus()}
function closeModal(){$('#overlay').hidden=true;$('#overlay').replaceChildren();submitModal=null}
const progress=p=>`<div class="progress"><i style="width:${pct(p)}%"></i></div>`;
const empty=(text,button='')=>`<div class="empty"><span class="svg-icon empty-icon" style="--icon: url('./assets/icons/empty.svg')"></span><p>${esc(text)}</p>${button}</div>`;
const ctx=()=>{const subs=new Map(S().data.subtasks.map(x=>[x.id,x])),kpis=new Map(S().data.kpis.map(x=>[x.id,x]));return {subs,kpis,forTask:t=>{const sub=subs.get(t.subtaskId),kpi=kpis.get(sub?.kpiId);return {sub,kpi}}}};
function route(view,params={}){document.body.classList.remove('nav-open');setState({view,...params});const q=new URLSearchParams({view,...(params.openSub?{subtaskId:params.openSub}:{})});history.replaceState(null,'',`?${q}`);render();if(params.openSub)setTimeout(()=>openSubtask(params.openSub),0)}

function render(){const s=S();$('#pageTitle').textContent=titles[s.view];$('#period').value=s.period;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===s.view));({dashboard:dashboardTaskWeighted,kpi:kpiTaskWeighted,planning:planningEnhanced,payroll:payrollWithItems,reports:reportsTaskWeighted,backup:backup,settings:settings}[s.view]||dashboardTaskWeighted)()}
function taskCheck(t){const icon=t.completed?`<span class="svg-icon" style="--icon: url('./assets/icons/check.svg'); width: 14px; height: 14px;"></span>`:'';return `<button class="check ${t.completed?'done':''}" data-toggle-task="${t.id}" aria-label="Đổi trạng thái">${icon}</button>`}
function dashboard(){const d=S().data,done=d.tasks.filter(x=>x.completed).length,urgentDone=d.urgentTasks.filter(x=>x.completed).length,week=monthWeeks(S().period).find(w=>w.days.includes(today())),weekTasks=d.tasks.filter(t=>week&&t.date>=week.start&&t.date<=week.end),over=d.tasks.filter(t=>!t.completed&&t.date&&t.date<today()),uns=d.tasks.filter(t=>!t.date),todayTasks=d.tasks.filter(t=>t.date===today()).sort((a,b)=>(a.startTime||'99').localeCompare(b.startTime||'99'));$('#content').innerHTML=`<div class="hero"><div><span>THÁNG ${S().period.slice(5)}/${S().period.slice(0,4)}</span><h2>${d.settings.displayName?`Chào ${esc(d.settings.displayName)}, `:''}mọi việc đang đi đúng hướng.</h2></div><b>${d.tasks.length?pct({done,total:d.tasks.length}):0}%<small>tiến độ tháng</small></b></div><div class="metric-grid"><article><span>KPI</span><b>${d.kpis.length}</b><small>${d.kpis.filter(k=>pct(kpiProgress(k,d.subtasks,d.tasks))===100).length} hoàn thành</small></article><article><span>Sub-task</span><b>${d.subtasks.length}</b><small>${d.subtasks.filter(s=>pct(subProgress(s,d.tasks))===100).length} hoàn thành</small></article><article><span>Task</span><b>${d.tasks.length}</b><small>${done} hoàn thành</small></article><article class="urgent"><span>Việc gấp</span><b>${d.urgentTasks.length}</b><small>${urgentDone} hoàn thành</small></article></div><div class="dash-grid"><section class="panel"><div class="section-title"><h3>Tiến độ KPI</h3><button data-go="kpi">Xem tất cả</button></div>${d.kpis.map(k=>{const p=kpiProgress(k,d.subtasks,d.tasks);return `<button class="kpi-progress" data-open-kpi="${k.id}"><span><b>${esc(k.name)}</b><small>${p.done}/${p.total} Sub-task</small></span>${progress(p)}<strong>${pct(p)}%</strong></button>`}).join('')||empty('Chưa có KPI.')}</section><section class="panel"><div class="section-title"><h3>Tuần này</h3><span>${weekTasks.length} Task</span></div><div class="big-stat">${weekTasks.filter(t=>t.completed).length}<small>đã hoàn thành</small></div><div class="big-stat red">${d.urgentTasks.filter(u=>week&&u.date>=week.start&&u.date<=week.end).length}<small>việc gấp</small></div></section><section class="panel"><div class="section-title"><h3>Cần chú ý</h3></div><button class="attention" data-plan-filter="overdue"><b>${over.length}</b><span>Task quá hạn</span></button><button class="attention" data-plan-filter="unscheduled"><b>${uns.length}</b><span>Task chưa có lịch</span></button></section><section class="panel"><div class="section-title"><h3>Lịch hôm nay</h3><button data-today>Hôm nay</button></div>${todayTasks.map(t=>`<div class="agenda-row"><time>${t.startTime?.slice(0,5)||'—'}</time>${taskCheck(t)}<button data-edit-task="${t.id}"><b>${esc(t.name)}</b><small>${esc(ctx().forTask(t).sub?.name||'')}</small></button></div>`).join('')||empty('Hôm nay chưa có Task.')}</section></div>`}

function kpiView(){const d=S().data,q=norm(S().filters.query),status=S().filters.status,week=S().filters.week;const rows=d.kpis.filter(k=>{const ss=d.subtasks.filter(s=>s.kpiId===k.id),match=!q||norm([k.name,k.note,...ss.map(s=>s.name)].join(' ')).includes(q),state=status==='all'||(status==='done')===(pct(kpiProgress(k,d.subtasks,d.tasks))===100),wk=week==='all'||ss.some(s=>String(s.weekNumber)===week);return match&&state&&wk});$('#content').innerHTML=`<div class="toolbar"><div class="filters"><input id="kpiSearch" placeholder="Tìm KPI hoặc Sub-task" value="${esc(S().filters.query)}"><select id="kpiStatus"><option value="all">Tất cả trạng thái</option><option value="open" ${status==='open'?'selected':''}>Chưa hoàn thành</option><option value="done" ${status==='done'?'selected':''}>Hoàn thành</option></select><select id="kpiWeek"><option value="all">Tất cả tuần</option>${monthWeeks(S().period).map(w=>`<option value="${w.number}" ${week===String(w.number)?'selected':''}>Tuần ${w.number}</option>`).join('')}</select></div><button class="btn primary" data-add-kpi>+ Tạo KPI</button></div><div class="kpi-list">${rows.map(k=>{const ss=d.subtasks.filter(s=>s.kpiId===k.id),p=kpiProgress(k,d.subtasks,d.tasks);return `<details class="kpi-card" data-kpi="${k.id}" open><summary><div class="kpi-main"><span class="ring">${pct(p)}%</span><div><h3>${esc(k.name)}</h3><p>${ss.length} Sub-task · ${p.done}/${p.total} hoàn thành</p>${progress(p)}</div></div><div class="actions"><button data-add-sub="${k.id}">+ Sub-task</button><button data-edit-kpi="${k.id}">Sửa</button><button data-delete="kpis:${k.id}">Xóa</button></div></summary><div class="subtask-list">${ss.map(s=>subRow(s)).join('')||empty('KPI này chưa có Sub-task.',`<button class="btn ghost" data-add-sub="${k.id}">+ Thêm Sub-task</button>`)}</div></details>`}).join('')||empty(`Chưa có KPI trong tháng ${S().period}.`,`<button class="btn primary" data-add-kpi>+ Tạo KPI đầu tiên</button>`)}</div>`}
function subRow(s){const d=S().data,p=subProgress(s,d.tasks);return `<div class="subtask-row"><button class="check ${pct(p)===100?'done':''}" data-toggle-sub="${s.id}">${pct(p)===100?'✓':''}</button><button class="sub-name" data-open-sub="${s.id}"><b>${esc(s.name)}</b><small>${s.weekNumber?`Tuần ${String(s.weekNumber).padStart(2,'0')}`:'Chưa xác định tuần'} · ${s.startDate?`${shortDate(s.startDate)} → ${shortDate(s.endDate||s.startDate)}`:'Chưa có lịch cụ thể'} · ${p.done}/${p.total} Task</small></button><button data-edit-sub="${s.id}">Sửa</button></div>`}
function openSubtask(id){const d=S().data,s=d.subtasks.find(x=>x.id===id);if(!s)return;const k=d.kpis.find(x=>x.id===s.kpiId),tasks=d.tasks.filter(t=>t.subtaskId===id).sort((a,b)=>a.sortOrder-b.sortOrder);modal(s.name,`<div class="breadcrumb">${esc(k?.name)} › ${esc(s.name)}</div><div class="sub-meta"><span>${s.weekNumber?`Tuần ${s.weekNumber}`:'Chưa xác định tuần'}</span><span>${s.startDate?`${fmtDate(s.startDate)} → ${fmtDate(s.endDate||s.startDate)}`:'Chưa có lịch cụ thể'}</span></div>${s.note?`<p class="note">${esc(s.note)}</p>`:''}<div class="section-title"><h3>TASK</h3><button type="button" data-add-task="${s.id}">+ Thêm Task</button></div><div class="modal-task-list">${tasks.map(t=>`<div class="modal-task">${taskCheck(t)}<button type="button" data-edit-task="${t.id}"><b>${esc(t.name)}</b><small>${timeRange(t)}</small></button><button type="button" data-delete="tasks:${t.id}">×</button></div>`).join('')||empty('Sub-task này chưa có Task.')}</div><div class="modal-progress"><b>${subProgress(s,d.tasks).done}/${subProgress(s,d.tasks).total} hoàn thành</b>${progress(subProgress(s,d.tasks))}</div>`,()=>{closeModal();return false},{wide:true,save:'Đóng'})}

function planning(){const d=S().data,view=S().calendarView,uns=d.tasks.filter(t=>!t.date),weeks=monthWeeks(S().period);$('#content').innerHTML=`<div class="plan-toolbar"><div class="segmented"><button data-cal-view="month" class="${view==='month'?'active':''}">Tháng</button><button data-cal-view="week" class="${view==='week'?'active':''}">Tuần</button><button data-cal-view="3day" class="${view==='3day'?'active':''}">3 ngày</button></div><button class="btn ghost" data-today>Hôm nay</button><button class="btn ghost" data-add-urgent>+ Việc gấp</button><button class="btn primary" data-calendar-task>+ Task</button></div><div class="planning-layout"><aside class="plan-side"><div class="side-tabs"><button class="active">KPI</button><button>Chưa xếp lịch <span>${uns.length}</span></button></div><div class="unscheduled"><h4>CHƯA CÓ NGÀY</h4>${d.subtasks.filter(s=>d.tasks.some(t=>t.subtaskId===s.id&&!t.date)).map(s=>{const n=d.tasks.filter(t=>t.subtaskId===s.id&&!t.date).length;return `<button data-open-sub="${s.id}"><b>${esc(s.name)}</b><small>${s.weekNumber?'Tuần '+s.weekNumber:'Chưa xác định tuần'} · ${n} Task</small></button>`}).join('')||empty('Tất cả công việc đã được xếp lịch.')}</div><div class="tree"><h4>KPI TREE</h4>${d.kpis.map(k=>`<details open><summary>${esc(k.name)}</summary>${d.subtasks.filter(s=>s.kpiId===k.id).map(s=>`<button data-open-sub="${s.id}">${esc(s.name)}<small>${d.tasks.filter(t=>t.subtaskId===s.id).length} Task</small></button>`).join('')}</details>`).join('')}</div></aside><section class="calendar-wrap">${view==='month'?monthCalendar():view==='week'?weekCalendar(weeks):threeDay()}</section></div>`}
function dayGroups(day){const d=S().data,{subs}=ctx(),rows=d.tasks.filter(t=>t.date===day),map=new Map();rows.forEach(t=>{const a=map.get(t.subtaskId)||[];a.push(t);map.set(t.subtaskId,a)});return [...map].map(([id,tasks])=>({sub:subs.get(id),tasks}))}
function monthCalendar(){const d=S().data,days=monthDays(S().period),offset=((new Date(`${days[0]}T12:00:00`).getDay()||7)-1);return `<div class="month-calendar"><div class="weekdays">${['T2','T3','T4','T5','T6','T7','CN'].map(x=>`<b>${x}</b>`).join('')}</div><div class="month-grid">${Array(offset).fill('<div class="day-cell muted"></div>').join('')}${days.map(day=>{const groups=dayGroups(day),urg=d.urgentTasks.filter(u=>u.date===day);return `<article class="day-cell ${day===today()?'today':''}"><header><b>${Number(day.slice(-2))}</b><button data-day-add="${day}">+</button></header>${groups.length||urg.length?`<div class="day-counts"><span>${groups.reduce((n,g)=>n+g.tasks.length,0)} Task</span>${urg.length?`<span class="red">${urg.length} Gấp</span>`:''}</div>`:''}${groups.slice(0,3).map(g=>`<button class="cal-group" data-cal-group="${day}:${g.sub?.id}"><span>${esc(g.sub?.name||'Task')}</span><b>${g.tasks.length}</b></button>`).join('')}${urg.slice(0,2).map(u=>`<button class="cal-urgent" data-edit-urgent="${u.id}">${esc(u.name)}</button>`).join('')}</article>`}).join('')}</div></div>`}
function weekCalendar(weeks){const anchor=S().anchorDate||today(),week=weeks.find(w=>w.days.includes(anchor))||weeks[0];return `<div class="week-calendar"><header><h3>Tuần ${week.number}</h3><span>${fmtDate(week.start)} → ${fmtDate(week.end)}</span></header><div class="week-columns">${week.days.map(day=>`<section><h4>${weekday(day)} <b>${shortDate(day)}</b></h4><div class="no-time"><small>CHƯA XẾP GIỜ</small>${S().data.tasks.filter(t=>t.date===day&&!t.startTime).map(t=>miniTask(t)).join('')}</div>${S().data.tasks.filter(t=>t.date===day&&t.startTime).sort((a,b)=>a.startTime.localeCompare(b.startTime)).map(t=>miniTask(t)).join('')}${S().data.urgentTasks.filter(u=>u.date===day).map(u=>`<button class="mini-task urgent" data-edit-urgent="${u.id}"><time>${u.startTime?.slice(0,5)||'—'}</time><b>${esc(u.name)}</b></button>`).join('')}</section>`).join('')}</div></div>`}
function miniTask(t){return `<button class="mini-task ${t.completed?'complete':''}" data-edit-task="${t.id}"><time>${t.startTime?.slice(0,5)||'—'}</time><b>${esc(t.name)}</b><small>${esc(ctx().forTask(t).sub?.name||'')}</small></button>`}
function threeDay(){const base=new Date(`${S().anchorDate||today()}T12:00:00`),days=[-1,0,1].map(n=>{const x=new Date(base);x.setDate(x.getDate()+n);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`});return `<div class="three-day">${days.map((day,i)=>`<section><header><span>${['HÔM QUA','HÔM NAY','NGÀY MAI'][i]}</span><h3>${weekday(day)}, ${fmtDate(day)}</h3></header><div class="no-time"><small>CHƯA XẾP GIỜ</small>${S().data.tasks.filter(t=>t.date===day&&!t.startTime).map(miniTask).join('')||'<i>Không có</i>'}</div><div class="timeline">${S().data.tasks.filter(t=>t.date===day&&t.startTime).sort((a,b)=>a.startTime.localeCompare(b.startTime)).map(miniTask).join('')}${S().data.urgentTasks.filter(u=>u.date===day).map(u=>`<button class="mini-task urgent" data-edit-urgent="${u.id}"><time>${u.startTime?.slice(0,5)||'—'}</time><b>${esc(u.name)}</b></button>`).join('')}</div></section>`).join('')}</div>`}

function payroll(){const d=S().data,p=d.payrolls[0],total=p?Number(p.baseSalary)+Number(p.kpiBonus)+Number(p.otherAdjustment)+Number(p.attendanceAdjustment):0,labels={leave:'Nghỉ phép',unpaid_leave:'Nghỉ không lương',late:'Đi trễ',early_leave:'Về sớm',business_trip:'Công tác',other:'Khác'};$('#content').innerHTML=`<div class="metric-grid salary"><article><span>TỔNG LƯƠNG DỰ KIẾN</span><b>${money(total)}</b><small>KPI: +${money(p?.kpiBonus||0)}</small></article><article><span>NGÀY CÔNG / NGHỈ</span><b>${d.attendanceEvents.filter(x=>x.type.includes('leave')).length} ngày nghỉ</b><small>${d.attendanceEvents.filter(x=>x.type==='late').length} lần đi trễ · ${d.attendanceEvents.filter(x=>x.type==='early_leave').length} lần về sớm</small></article></div><div class="two-col"><section class="panel"><div class="section-title"><h3>Bảng lương</h3><button data-edit-payroll>${p?'Chỉnh sửa':'Tạo bảng lương'}</button></div>${p?`<div class="salary-lines"><span>Lương cơ bản <b>${money(p.baseSalary)}</b></span><span>KPI <b>${money(p.kpiBonus)}</b></span><span>Khoản khác <b>${money(p.otherAdjustment)}</b></span><span>Chấm công <b>${money(p.attendanceAdjustment)}</b></span><strong>Dự kiến <b>${money(total)}</b></strong></div>`:empty('Chưa có bảng lương tháng này.')}</section><section class="panel"><div class="section-title"><h3>Nghỉ / đi trễ / công tác</h3><button data-add-attendance>+ Thêm lịch</button></div>${d.attendanceEvents.map(x=>`<button class="attendance" data-edit-attendance="${x.id}"><span><b>${labels[x.type]}</b><small>${fmtDate(x.startDate)} → ${fmtDate(x.endDate)} · ${x.approvalStatus}</small></span><strong>${money(x.salaryAdjustment)}</strong></button>`).join('')||empty('Chưa có dữ liệu chấm công.')}</section></div>`}
function reports(){const d=S().data,done=d.tasks.filter(t=>t.completed),pending=d.tasks.filter(t=>!t.completed),over=pending.filter(t=>t.date&&t.date<today());$('#content').innerHTML=`<div class="report-filters"><select><option>Tháng ${S().period}</option></select><select><option>Tất cả KPI</option></select><select><option>Tất cả trạng thái</option></select></div><div class="metric-grid"><article><span>KPI</span><b>${d.kpis.length}</b><small>${d.kpis.filter(k=>pct(kpiProgress(k,d.subtasks,d.tasks))===100).length} hoàn thành</small></article><article><span>Sub-task</span><b>${d.subtasks.length}</b><small>${d.subtasks.filter(s=>pct(subProgress(s,d.tasks))===100).length} hoàn thành</small></article><article><span>Task</span><b>${d.tasks.length}</b><small>${done.length} hoàn thành</small></article><article class="urgent"><span>Việc gấp</span><b>${d.urgentTasks.length}</b><small>${d.urgentTasks.filter(u=>u.completed).length} hoàn thành</small></article></div><div class="two-col"><section class="panel report-tree"><h3>Công việc hoàn thành</h3>${d.kpis.map(k=>{const tasks=done.filter(t=>d.subtasks.some(s=>s.id===t.subtaskId&&s.kpiId===k.id));return tasks.length?`<div><b>✓ ${esc(k.name)}</b>${tasks.map(t=>`<span>✓ ${esc(t.name)}</span>`).join('')}</div>`:''}).join('')||empty('Chưa có công việc hoàn thành.')}</section><section class="panel report-tree"><h3>Chưa hoàn thành</h3>${pending.map(t=>`<button data-edit-task="${t.id}"><b>○ ${esc(t.name)}</b><small>${esc(ctx().forTask(t).sub?.name||'')}${over.includes(t)?' · Quá hạn':''}</small></button>`).join('')||empty('Tất cả Task đã hoàn thành.')}</section></div><section class="panel"><div class="section-title"><h3>Việc phát sinh</h3><b>${d.urgentTasks.length} việc</b></div>${d.urgentTasks.map(u=>`<div class="simple-line"><span>${u.completed?'✓':'○'} ${esc(u.name)}</span><small>${fmtDate(u.date)}</small></div>`).join('')||empty('Không có việc phát sinh.')}</section>`}
function backup(){$('#content').innerHTML=`<div class="backup-grid"><section class="panel backup-card"><span class="feature-icon svg-icon" style="--icon: url('./assets/icons/download.svg')"></span><h2>Backup toàn bộ hệ thống</h2><p>Bao gồm KPI, Sub-task, Task, việc gấp, lương, chấm công và cài đặt.</p><div class="checklist">✓ JSON có version<br>✓ Giữ nguyên UUID và quan hệ<br>✓ Dùng để chuyển hosting</div><button class="btn primary" data-export>Xuất Backup JSON</button></section><section class="panel backup-card"><span class="feature-icon svg-icon" style="--icon: url('./assets/icons/upload.svg')"></span><h2>Import / Khôi phục</h2><p>File sẽ được kiểm tra trước khi thay thế dữ liệu. Supabase thực hiện restore trong một transaction.</p><label class="file"><input id="restoreFile" type="file" accept="application/json">Chọn file backup</label><div id="restorePreview"></div></section></div>`}
function settings(){$('#content').innerHTML=`<section class="panel settings"><h2>Cài đặt</h2><p>Flow KPI V3 · nguồn dữ liệu ${S().demo?'Demo trên trình duyệt':'Supabase'}</p><div class="setting-row"><span><b>Tháng đang làm việc</b><small>${S().period}</small></span></div><div class="setting-row"><span><b>Tuần bắt đầu từ Thứ Hai</b><small>Tuần trong tháng có thể từ 1 đến 6.</small></span></div><div class="setting-row"><span><b>Source of truth</b><small>KPI và Calendar cùng đọc/ghi một Task.</small></span></div></section>`}

function kpiForm(item={}){modal(item.id?'Chỉnh sửa KPI':'Tạo KPI',`${input('name','Tên KPI',item.name,'text','required maxlength=500')}${area('note','Ghi chú',item.note)}`,async v=>{const m=await api.month(S().period);await run(()=>api.save('kpis',{...item,...v,monthId:item.monthId||m.id,sortOrder:item.sortOrder??S().data.kpis.length}),'Đã lưu KPI');await refresh();return true})}
function subForm(kpiId,item={}){modal(item.id?'Chỉnh sửa Sub-task':'Thêm Sub-task',`<div class="form-grid">${input('name','Tên Sub-task',item.name,'text','required maxlength=500')}${select('weekNumber','Tuần',item.weekNumber||'',[['','Chưa xác định'],...monthWeeks(S().period).map(w=>[w.number,`Tuần ${w.number}`])])}${input('startDate','Từ ngày',item.startDate,'date')}${input('endDate','Đến ngày',item.endDate,'date')}${area('note','Ghi chú',item.note)}</div>`,async v=>{if(v.startDate&&v.endDate&&v.endDate<v.startDate){toast('Ngày kết thúc phải sau ngày bắt đầu.',true);return false}await run(()=>api.save('subtasks',{...item,...v,kpiId,weekNumber:v.weekNumber?Number(v.weekNumber):null,startDate:v.startDate||null,endDate:v.endDate||null,completed:item.completed||false,sortOrder:item.sortOrder??S().data.subtasks.filter(s=>s.kpiId===kpiId).length}),'Đã lưu Sub-task');await refresh();return true},{wide:true})}
function taskForm(subtaskId,item={},prefill={}){modal(item.id?'Chỉnh sửa Task':'Thêm Task',`<div class="form-grid">${input('name','Tên Task',item.name,'text','required maxlength=500')}${input('date','Ngày',item.date||prefill.date,'date')}${input('startTime','Giờ bắt đầu',item.startTime,'time')}${input('endTime','Giờ kết thúc',item.endTime,'time')}${select('completed','Trạng thái',String(item.completed||false),[['false','Chưa hoàn thành'],['true','Hoàn thành']])}${area('note','Ghi chú',item.note)}</div>`,async v=>{if(!v.date&&(v.startTime||v.endTime)){toast('Không thể đặt giờ khi chưa có ngày.',true);return false}if(v.startTime&&v.endTime&&v.endTime<=v.startTime){toast('Giờ kết thúc phải sau giờ bắt đầu.',true);return false}const complete=v.completed==='true';await run(()=>api.save('tasks',{...item,...v,subtaskId,date:v.date||null,startTime:v.startTime||null,endTime:v.endTime||null,completed:complete,completedAt:complete?(item.completedAt||new Date().toISOString()):null,sortOrder:item.sortOrder??S().data.tasks.filter(t=>t.subtaskId===subtaskId).length}),'Đã lưu Task');await refresh();return true},{wide:true})}
function calendarTask(day=''){const d=S().data;if(!d.kpis.length)return toast('Hãy tạo KPI và Sub-task trước.',true);modal('Tạo Task từ Calendar',`<div class="form-grid">${input('name','Tên Task','','text','required')}${select('kpiId','Thuộc KPI',d.kpis[0].id,d.kpis.map(k=>[k.id,k.name]),'id="taskKpi"')}${select('subtaskId','Thuộc Sub-task','',d.subtasks.filter(s=>s.kpiId===d.kpis[0].id).map(s=>[s.id,s.name]),'id="taskSub"')}${input('date','Ngày',day,'date')}${input('startTime','Bắt đầu','','time')}${input('endTime','Kết thúc','','time')}${area('note','Ghi chú','')}</div>`,async v=>{if(!v.subtaskId){toast('KPI này chưa có Sub-task.',true);return false}await run(()=>api.save('tasks',{name:v.name,subtaskId:v.subtaskId,date:v.date||null,startTime:v.startTime||null,endTime:v.endTime||null,note:v.note,completed:false,sortOrder:999}),'Đã tạo Task');await refresh();return true},{wide:true});$('#taskKpi').onchange=e=>{$('#taskSub').innerHTML=d.subtasks.filter(s=>s.kpiId===e.target.value).map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}}
function urgentForm(item={},date=''){const d=S().data;modal(item.id?'Chỉnh sửa việc gấp':'Thêm việc gấp',`<div class="form-grid">${input('name','Tên',item.name,'text','required')}${input('date','Ngày',item.date||date||today(),'date','required')}${input('startTime','Bắt đầu',item.startTime,'time')}${input('endTime','Kết thúc',item.endTime,'time')}${select('relatedKpiId','Liên quan KPI',item.relatedKpiId||'',[['','Không'],...d.kpis.map(k=>[k.id,k.name])])}${select('relatedSubtaskId','Sub-task',item.relatedSubtaskId||'',[['','Không'],...d.subtasks.map(s=>[s.id,s.name])])}${input('category','Phân loại',item.category)}${select('completed','Trạng thái',String(item.completed||false),[['false','Chưa hoàn thành'],['true','Hoàn thành']])}${area('note','Ghi chú',item.note)}</div>`,async v=>{const m=await api.month(S().period),complete=v.completed==='true';await run(()=>api.save('urgentTasks',{...item,...v,monthId:item.monthId||m.id,startTime:v.startTime||null,endTime:v.endTime||null,relatedKpiId:v.relatedKpiId||null,relatedSubtaskId:v.relatedSubtaskId||null,category:v.category||null,completed:complete,completedAt:complete?(item.completedAt||new Date().toISOString()):null}),'Đã lưu việc gấp');await refresh();return true},{wide:true})}
function payrollForm(){const p=S().data.payrolls[0]||{};modal(p.id?'Chỉnh sửa bảng lương':'Tạo bảng lương',`<div class="payroll-modal"><div class="form-grid">${input('baseSalary','Lương cơ bản',p.baseSalary||0,'number','step=1000')}${input('kpiBonus','KPI bonus',p.kpiBonus||0,'number','step=1000')}${input('otherAdjustment','Khoản khác',p.otherAdjustment||0,'number','step=1000')}${input('attendanceAdjustment','Điều chỉnh chấm công',p.attendanceAdjustment||0,'number','step=1000')}${area('note','Ghi chú',p.note)}</div><aside><h3>Tham chiếu hoàn thành</h3>${S().data.subtasks.filter(s=>pct(subProgress(s,S().data.tasks))===100).map(s=>`<span>✓ ${esc(s.name)}</span>`).join('')||'<small>Chưa có Sub-task hoàn thành.</small>'}<h3>Việc gấp</h3>${S().data.urgentTasks.filter(u=>u.completed).map(u=>`<span>✓ ${esc(u.name)}</span>`).join('')||'<small>Chưa có việc gấp hoàn thành.</small>'}</aside></div>`,async v=>{const m=await api.month(S().period);await run(()=>api.save('payrolls',{...p,...Object.fromEntries(Object.entries(v).map(([k,x])=>[k,k==='note'?x:Number(x)||0])),monthId:p.monthId||m.id}),'Đã lưu bảng lương');await refresh();return true},{wide:true})}
function attendanceForm(item={}){modal(item.id?'Chỉnh sửa lịch':'Thêm lịch',`<div class="form-grid">${select('type','Loại',item.type||'leave',[['leave','Nghỉ phép'],['unpaid_leave','Nghỉ không lương'],['late','Đi trễ'],['early_leave','Về sớm'],['business_trip','Công tác'],['other','Khác']])}${input('startDate','Từ ngày',item.startDate||today(),'date','required')}${input('endDate','Đến ngày',item.endDate||today(),'date','required')}${input('startTime','Từ giờ',item.startTime,'time')}${input('endTime','Đến giờ',item.endTime,'time')}${select('approvalStatus','Trạng thái duyệt',item.approvalStatus||'draft',[['draft','Chưa gửi'],['pending','Chờ duyệt'],['approved','Đã duyệt'],['rejected','Từ chối']])}${input('salaryAdjustment','Ảnh hưởng lương',item.salaryAdjustment||0,'number','step=1000')}${area('note','Ghi chú',item.note)}</div>`,async v=>{const m=await api.month(S().period);await run(()=>api.save('attendanceEvents',{...item,...v,monthId:item.monthId||m.id,startTime:v.startTime||null,endTime:v.endTime||null,salaryAdjustment:Number(v.salaryAdjustment)||0}),'Đã lưu chấm công');await refresh();return true},{wide:true})}
function confirmDelete(name,id){const labels={kpis:'KPI cùng toàn bộ Sub-task và Task',subtasks:'Sub-task cùng toàn bộ Task',tasks:'Task',urgentTasks:'việc gấp',attendanceEvents:'lịch chấm công'};modal('Xác nhận xóa',`<div class="danger-box">Xóa ${labels[name]||'mục này'}? Hành động này không thể hoàn tác.</div>`,async()=>{await run(()=>api.remove(name,id),'Đã xóa');closeModal();await refresh();return false},{danger:true,save:'Xóa'})}

document.addEventListener('click',async e=>{const b=e.target.closest('button,[data-open-sub]');if(!b)return;const d=S().data;if(b.dataset.close!=null)return closeModal();if(b.dataset.view)return route(b.dataset.view);if(b.dataset.go)return route(b.dataset.go);if(b.dataset.addKpi!=null)return kpiForm();if(b.dataset.editKpi)return kpiForm(d.kpis.find(x=>x.id===b.dataset.editKpi));if(b.dataset.addSub)return subForm(b.dataset.addSub);if(b.dataset.editSub){const x=d.subtasks.find(x=>x.id===b.dataset.editSub);return subForm(x.kpiId,x)}if(b.dataset.openSub)return openSubtask(b.dataset.openSub);if(b.dataset.addTask)return taskForm(b.dataset.addTask);if(b.dataset.editTask){const x=d.tasks.find(x=>x.id===b.dataset.editTask);return taskForm(x.subtaskId,x)}if(b.dataset.toggleTask){const x=d.tasks.find(x=>x.id===b.dataset.toggleTask);await run(()=>api.save('tasks',{...x,completed:!x.completed,completedAt:!x.completed?new Date().toISOString():null}));return refresh()}if(b.dataset.toggleSub){const s=d.subtasks.find(x=>x.id===b.dataset.toggleSub),remaining=d.tasks.filter(t=>t.subtaskId===s.id&&!t.completed);if(remaining.length&&!s.completed)return modal('Hoàn thành Sub-task',`<div class="warning">Sub-task này còn ${remaining.length} Task chưa hoàn thành. Bạn có muốn đánh dấu toàn bộ Task là hoàn thành không?</div>`,async()=>{await run(()=>api.completeSubtask(s,true),'Đã hoàn thành Sub-task');await refresh();return true},{save:'Hoàn thành tất cả'});await run(()=>api.completeSubtask(s,!s.completed));return refresh()}if(b.dataset.delete){const [n,id]=b.dataset.delete.split(':');return confirmDelete(n,id)}if(b.dataset.calView){setState({calendarView:b.dataset.calView});return planning()}if(b.dataset.calendarTask!=null)return calendarTask();if(b.dataset.dayAdd)return calendarTask(b.dataset.dayAdd);if(b.dataset.addUrgent!=null)return urgentForm();if(b.dataset.editUrgent)return urgentForm(d.urgentTasks.find(x=>x.id===b.dataset.editUrgent));if(b.dataset.calGroup){const [,sid]=b.dataset.calGroup.split(':');return openSubtask(sid)}if(b.dataset.today!=null){setState({anchorDate:today(),calendarView:S().view==='planning'?'3day':S().calendarView});return route('planning')}if(b.dataset.planFilter){setState({calendarView:'month'});return route('planning')}if(b.dataset.editPayroll!=null)return payrollForm();if(b.dataset.addAttendance!=null)return attendanceForm();if(b.dataset.editAttendance)return attendanceForm(d.attendanceEvents.find(x=>x.id===b.dataset.editAttendance));if(b.dataset.export!=null){const all=await run(()=>api.exportAll()),payload={backup_version:'1.0',exported_at:new Date().toISOString(),app_version:'3.0.0',data:all};return download(JSON.stringify(payload,null,2),`flow-kpi-v3-${today()}.json`)}if(b.dataset.openKpi){route('kpi');setTimeout(()=>document.querySelector(`[data-kpi="${b.dataset.openKpi}"]`)?.scrollIntoView({behavior:'smooth'}),0)}});
document.addEventListener('input',e=>{if(e.target.id==='kpiSearch'){S().filters.query=e.target.value;kpiView()}});document.addEventListener('change',e=>{if(e.target.id==='kpiStatus'){S().filters.status=e.target.value;kpiView()}if(e.target.id==='kpiWeek'){S().filters.week=e.target.value;kpiView()}if(e.target.id==='restoreFile'){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(p.backup_version!=='1.0'||!p.data?.months)throw Error('File backup không hợp lệ');$('#restorePreview').innerHTML=`<div class="restore-preview"><b>${p.data.kpis?.length||0} KPI · ${p.data.subtasks?.length||0} Sub-task · ${p.data.tasks?.length||0} Task</b><button id="confirmRestore" class="btn danger">Khôi phục dữ liệu</button></div>`;$('#confirmRestore').onclick=()=>modal('Khôi phục dữ liệu',`<div class="danger-box">Dữ liệu hiện tại sẽ được thay thế bằng file backup đã chọn.</div>`,async()=>{await run(()=>api.restore(p),'Khôi phục thành công');await refresh();return true},{danger:true,save:'Khôi phục'})}catch(x){toast(x.message,true)}};r.readAsText(f)}});
$('#overlay').addEventListener('click',e=>{if(e.target===$('#overlay'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
$('#period').onchange=async e=>{setState({period:e.target.value,anchorDate:`${e.target.value}-01`});await refresh()};function shift(n){const [y,m]=S().period.split('-').map(Number),x=new Date(y,m-1+n,1);setState({period:`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`,anchorDate:null});refresh()}$('#prevMonth').onclick=()=>shift(-1);$('#nextMonth').onclick=()=>shift(1);$('#menuButton').onclick=()=>document.body.classList.toggle('nav-open');document.addEventListener('click',e=>{if(document.body.classList.contains('nav-open')&&!e.target.closest('.sidebar')&&!e.target.closest('#menuButton')){document.body.classList.remove('nav-open')}});$('#logoutButton').onclick=async()=>{await api.signOut();$('#app').hidden=true;$('#auth').hidden=false;document.body.classList.remove('nav-open');window.scrollTo(0,0)};
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await enter(await run(()=>api.signIn($('#email').value,$('#password').value)))}catch(x){$('#authMessage').textContent=x.message}};$('#demoLogin').onclick=async()=>enter(await api.demoSignIn());async function enter(user){setState({user,demo:api.isDemo(),period:currentMonth()});$('#auth').hidden=true;$('#app').hidden=false;document.body.classList.remove('nav-open');window.scrollTo(0,0);await refresh();const q=new URLSearchParams(location.search);if(q.get('view'))route(q.get('view'),{openSub:q.get('subtaskId')})}
api.init(user=>{if(user&&!S().user)enter(user)}).catch(e=>$('#authMessage').textContent=e.message);

function dashboardTaskWeighted(){
  dashboard();
  const d=S().data,monthly=portfolioProgress(d.kpis,d.subtasks,d.tasks);
  const hero=$('.hero > b');
  if(hero)hero.innerHTML=`${pct(monthly)}%<small>tiến độ tháng theo công việc</small>`;
  const kpiMetric=$('.metric-grid article:first-child small');
  if(kpiMetric)kpiMetric.textContent=`${d.kpis.filter(k=>kpiIsHealthy(k,d.subtasks,d.tasks)).length} KPI đạt từ 85%`;
  document.querySelectorAll('.kpi-progress').forEach(row=>{
    const k=d.kpis.find(x=>x.id===row.dataset.openKpi),p=k&&kpiProgress(k,d.subtasks,d.tasks),meta=row.querySelector('small');
    if(meta&&p)meta.textContent=`${p.done}/${p.total} công việc${pct(p)>=85?' · Đạt':''}`;
    row.classList.toggle('healthy',!!p&&pct(p)>=85);
  });
}

function kpiTaskWeighted(){
  kpiView();
  const d=S().data;
  document.querySelectorAll('.kpi-card').forEach(card=>{
    const k=d.kpis.find(x=>x.id===card.dataset.kpi),p=k&&kpiProgress(k,d.subtasks,d.tasks),label=card.querySelector('.kpi-main p');
    if(label&&p){const subCount=d.subtasks.filter(s=>s.kpiId===k.id).length;label.textContent=`${subCount} Sub-task · ${p.done}/${p.total} công việc${pct(p)>=85?' · Đạt':''}`;}
    card.classList.toggle('healthy',!!p&&pct(p)>=85);
  });
}

function reportsTaskWeighted(){
  reports();
  const d=S().data,metric=$('.metric-grid article:first-child small');
  if(metric)metric.textContent=`${d.kpis.filter(k=>kpiIsHealthy(k,d.subtasks,d.tasks)).length} KPI đạt từ 85%`;
}

function payrollWithItems(){
  payroll();
  const p=S().data.payrolls[0],box=$('.salary-lines');
  if(!p||!box)return;
  const items=Array.isArray(p.adjustmentItems)?p.adjustmentItems:[];
  if(items.length){
    const details=document.createElement('div');
    details.className='salary-item-details';
    details.innerHTML=`<small>CHI TIẾT KHOẢN KHÁC</small>${items.map(item=>`<span class="${item.type==='penalty'?'penalty':'income'}"><i>${item.type==='penalty'?'−':'+'}</i>${esc(item.title)}<b>${money(item.amount)}</b></span>`).join('')}`;
    box.querySelector('strong')?.before(details);
  }
}

function payrollItemsForm(){
  const p=S().data.payrolls[0]||{};
  const initial=Array.isArray(p.adjustmentItems)&&p.adjustmentItems.length?p.adjustmentItems:(Number(p.otherAdjustment)?[{type:Number(p.otherAdjustment)<0?'penalty':'income',title:'Khoản khác',amount:Math.abs(Number(p.otherAdjustment))}]:[]);
  const row=item=>`<div class="pay-item-row" data-pay-item><select data-item-type><option value="income" ${item.type!=='penalty'?'selected':''}>Thu nhập</option><option value="penalty" ${item.type==='penalty'?'selected':''}>Khoản phạt</option></select><input data-item-title value="${esc(item.title||'')}" placeholder="Tên khoản"><input data-item-amount type="number" min="0" step="1000" value="${Math.abs(Number(item.amount)||0)}" placeholder="Số tiền"><button type="button" data-remove-item aria-label="Xóa">×</button></div>`;
  modal(p.id?'Chỉnh sửa bảng lương':'Tạo bảng lương',`<div class="payroll-editor"><div class="form-grid">${input('baseSalary','Lương cơ bản',p.baseSalary||0,'number','step=1000')}${input('kpiBonus','KPI bonus',p.kpiBonus||0,'number','step=1000')}${input('attendanceAdjustment','Điều chỉnh chấm công',p.attendanceAdjustment||0,'number','step=1000')}${area('note','Ghi chú',p.note)}</div><section class="pay-items-section"><div class="section-title"><div><h3>CÁC KHOẢN KHÁC</h3><p>Thêm từng khoản thu nhập hoặc khoản phạt.</p></div><strong id="itemsTotal">${money(p.otherAdjustment||0)}</strong></div><div id="payItemsList">${initial.map(row).join('')}</div><div class="item-add-actions"><button type="button" class="btn ghost" id="addIncome">+ Thu nhập</button><button type="button" class="btn penalty-btn" id="addPenalty">+ Khoản phạt</button></div></section></div>`,async(v,form)=>{
    const items=[...form.querySelectorAll('[data-pay-item]')].map(el=>({type:el.querySelector('[data-item-type]').value,title:el.querySelector('[data-item-title]').value.trim(),amount:Math.abs(Number(el.querySelector('[data-item-amount]').value)||0)})).filter(x=>x.title&&x.amount);
    const otherAdjustment=items.reduce((sum,x)=>sum+(x.type==='penalty'?-x.amount:x.amount),0),m=await api.month(S().period);
    await run(()=>api.save('payrolls',{...p,monthId:p.monthId||m.id,baseSalary:Number(v.baseSalary)||0,kpiBonus:Number(v.kpiBonus)||0,otherAdjustment,adjustmentItems:items,attendanceAdjustment:Number(v.attendanceAdjustment)||0,note:v.note||''}),'Đã lưu bảng lương');
    await refresh();return true;
  },{wide:true});
  const list=$('#payItemsList'),total=()=>{const sum=[...list.querySelectorAll('[data-pay-item]')].reduce((n,el)=>n+(el.querySelector('[data-item-type]').value==='penalty'?-1:1)*(Number(el.querySelector('[data-item-amount]').value)||0),0);$('#itemsTotal').textContent=money(sum)};
  const add=type=>{list.insertAdjacentHTML('beforeend',row({type,title:'',amount:0}));list.lastElementChild.querySelector('[data-item-title]').focus();total()};
  $('#addIncome').onclick=()=>add('income');$('#addPenalty').onclick=()=>add('penalty');list.addEventListener('click',e=>{if(e.target.closest('[data-remove-item]')){e.target.closest('[data-pay-item]').remove();total()}});list.addEventListener('input',total);list.addEventListener('change',total);
}

// Capture this action before the legacy fixed-field form handler.
document.addEventListener('click',e=>{if(!e.target.closest('[data-edit-payroll]'))return;e.preventDefault();e.stopImmediatePropagation();payrollItemsForm()},{capture:true});

function planningEnhanced(){
  planning();
  const s=S(),d=s.data,weeks=monthWeeks(s.period),activeWeek=weeks.find(w=>w.days.includes(s.anchorDate||today()))||weeks[0];
  const toolbar=$('.plan-toolbar');
  toolbar.innerHTML=`<div class="view-controls"><button data-plan-view="month" class="${s.calendarView==='month'?'active':''}">Tháng</button><label class="view-select ${s.calendarView==='week'?'active':''}"><span>Tuần</span><select id="planWeek">${weeks.map(w=>`<option value="${w.number}" ${w.number===activeWeek.number?'selected':''}>Tuần ${w.number} · ${shortDate(w.start)}–${shortDate(w.end)}</option>`).join('')}</select></label><label class="view-select ${s.calendarView==='3day'?'active':''}"><span>3 ngày quanh</span><input id="planThreeDay" type="date" value="${s.anchorDate||today()}"></label><button data-plan-view="custom" class="${s.calendarView==='custom'?'active':''}">Tùy chọn</button></div><div class="plan-actions"><button class="btn ghost" data-today>Hôm nay</button><button class="btn ghost" data-add-urgent>+ Việc gấp</button><button class="btn primary" data-calendar-task>+ Task</button></div>`;
  const mode=s.planningSidebar||'unscheduled',allTasks=d.tasks,visibleTasks=mode==='unscheduled'?allTasks.filter(t=>!t.date):allTasks;
  const emptySubs=d.subtasks.filter(sub=>!allTasks.some(t=>t.subtaskId===sub.id));
  const {subs,kpis}=ctx(),side=$('.plan-side');
  side.innerHTML=`<div class="planner-side-head"><h3>Công việc</h3><p>Kéo một việc vào ngày trên lịch để xếp lịch.</p></div><div class="side-tabs"><button data-planning-side="all" class="${mode==='all'?'active':''}">Tất cả <span>${allTasks.length+emptySubs.length}</span></button><button data-planning-side="unscheduled" class="${mode==='unscheduled'?'active':''}">Chưa xếp ngày <span>${allTasks.filter(t=>!t.date).length+emptySubs.length}</span></button></div><div class="flat-work-list">${visibleTasks.map(t=>{const sub=subs.get(t.subtaskId),kpi=kpis.get(sub?.kpiId);return `<article class="draggable-work ${t.completed?'complete':''}" draggable="true" data-drag-task="${t.id}"><div><b>${esc(t.name)}</b><small>${esc(sub?.name||'')} · ${esc(kpi?.name||'')}</small><em>${t.date?fmtDate(t.date):'Chưa có ngày'}${t.startTime?' · '+t.startTime.slice(0,5):''}</em></div><button data-edit-task="${t.id}" title="Sửa">•••</button></article>`}).join('')}${emptySubs.map(sub=>{const kpi=kpis.get(sub.kpiId);return `<article class="draggable-work empty-sub" draggable="true" data-drag-sub="${sub.id}"><div><b>${esc(sub.name)}</b><small>Sub-task chưa có Task · ${esc(kpi?.name||'')}</small><em>${sub.startDate?fmtDate(sub.startDate):'Chưa có ngày'}</em></div><button data-open-sub="${sub.id}">Mở</button></article>`}).join('')||empty(mode==='unscheduled'?'Tất cả công việc đã được xếp ngày.':'Chưa có công việc.')}</div>`;
  if(s.calendarView==='custom')$('.calendar-wrap').innerHTML=customRangeCalendar();
  document.querySelectorAll('.day-cell:not(.muted)').forEach(cell=>{const day=cell.querySelector('[data-day-add]')?.dataset.dayAdd;if(day){cell.dataset.openDay=day;cell.dataset.dropDay=day;cell.title='Click để xem công việc · Kéo Task vào để xếp lịch'}});
}

function customRangeCalendar(){
  const s=S(),days=monthDays(s.period),start=s.rangeStart||days[0],end=s.rangeEnd||start,lo=start<end?start:end,hi=start<end?end:start;
  const tasks=s.data.tasks.filter(t=>t.date&&t.date>=lo&&t.date<=hi).sort((a,b)=>a.date.localeCompare(b.date)||(a.startTime||'99').localeCompare(b.startTime||'99'));
  return `<div class="range-picker"><header><div><small>TÙY CHỌN KHOẢNG NGÀY</small><h3>${fmtDate(lo)} → ${fmtDate(hi)}</h3></div><p>Kéo từ ngày bắt đầu đến ngày kết thúc.</p></header><div class="range-weekdays">${['T2','T3','T4','T5','T6','T7','CN'].map(x=>`<b>${x}</b>`).join('')}</div><div class="range-days">${Array(((new Date(`${days[0]}T12:00:00`).getDay()||7)-1)).fill('<i></i>').join('')}${days.map(day=>`<button class="range-day ${day>=lo&&day<=hi?'selected':''}" data-range-day="${day}" data-drop-day="${day}">${Number(day.slice(-2))}</button>`).join('')}</div></div><div class="range-results"><div class="section-title"><h3>${tasks.length} Task trong khoảng đã chọn</h3></div>${tasks.map(t=>`<button data-edit-task="${t.id}" class="range-task"><time>${shortDate(t.date)}${t.startTime?' · '+t.startTime.slice(0,5):''}</time><span><b>${esc(t.name)}</b><small>${esc(ctx().forTask(t).sub?.name||'')}</small></span></button>`).join('')||empty('Không có Task trong khoảng ngày này.')}</div>`;
}

function openDayAgenda(day){
  const d=S().data,tasks=d.tasks.filter(t=>t.date===day).sort((a,b)=>(a.startTime||'99').localeCompare(b.startTime||'99')),urgent=d.urgentTasks.filter(u=>u.date===day).sort((a,b)=>(a.startTime||'99').localeCompare(b.startTime||'99'));
  modal(`${weekday(day)}, ${fmtDate(day)}`,`<div class="day-agenda-head"><span>${tasks.length} Task</span><span class="urgent-label">${urgent.length} việc gấp</span></div><div class="day-agenda-list">${tasks.map(t=>`<div class="day-agenda-row">${taskCheck(t)}<button type="button" data-edit-task="${t.id}"><div class="agenda-row-title"><time>${t.startTime?.slice(0,5)||'Chưa có giờ'}</time><b>${esc(t.name)}</b></div><small>${esc(ctx().forTask(t).sub?.name||'')}<i>•</i>${esc(ctx().forTask(t).kpi?.name||'')}</small></button></div>`).join('')||empty('Không có Task trong ngày này.')}${urgent.map(u=>`<div class="day-agenda-row urgent-row"><span>!</span><button type="button" data-edit-urgent="${u.id}"><div class="agenda-row-title"><time>${u.startTime?.slice(0,5)||'Chưa có giờ'}</time><b>${esc(u.name)}</b></div><small>Việc gấp / đột xuất</small></button></div>`).join('')}</div><div class="day-agenda-actions"><button type="button" class="btn urgent-action" data-popup-urgent="${day}">+ Việc gấp</button><button type="button" class="btn primary" data-popup-task="${day}">+ Task</button></div>`,()=>false,{wide:true,className:'day-modal',hideFooter:true});
}

document.addEventListener('click',e=>{
  const view=e.target.closest('[data-plan-view]');if(view){e.preventDefault();e.stopImmediatePropagation();setState({calendarView:view.dataset.planView});planningEnhanced();return}
  const side=e.target.closest('[data-planning-side]');if(side){e.preventDefault();e.stopImmediatePropagation();setState({planningSidebar:side.dataset.planningSide});planningEnhanced();return}
  const day=e.target.closest('[data-open-day]');if(day&&!e.target.closest('button')){e.preventDefault();openDayAgenda(day.dataset.openDay);return}
  const addTask=e.target.closest('[data-popup-task]');if(addTask){e.preventDefault();e.stopImmediatePropagation();closeModal();calendarTask(addTask.dataset.popupTask);return}
  const addUrgent=e.target.closest('[data-popup-urgent]');if(addUrgent){e.preventDefault();e.stopImmediatePropagation();closeModal();urgentForm({},addUrgent.dataset.popupUrgent)}
},{capture:true});

document.addEventListener('change',e=>{if(e.target.id==='planWeek'){const w=monthWeeks(S().period).find(x=>x.number===Number(e.target.value));setState({calendarView:'week',anchorDate:w?.start});planningEnhanced()}if(e.target.id==='planThreeDay'){setState({calendarView:'3day',anchorDate:e.target.value});planningEnhanced()}});
let rangeDragging=false,rangeOrigin=null;
document.addEventListener('pointerdown',e=>{const day=e.target.closest('[data-range-day]');if(!day)return;rangeDragging=true;rangeOrigin=day.dataset.rangeDay;setState({rangeStart:rangeOrigin,rangeEnd:rangeOrigin});e.preventDefault()});
document.addEventListener('pointerover',e=>{const day=e.target.closest('[data-range-day]');if(!rangeDragging||!day)return;S().rangeEnd=day.dataset.rangeDay;const lo=rangeOrigin<S().rangeEnd?rangeOrigin:S().rangeEnd,hi=rangeOrigin<S().rangeEnd?S().rangeEnd:rangeOrigin;document.querySelectorAll('[data-range-day]').forEach(x=>x.classList.toggle('selected',x.dataset.rangeDay>=lo&&x.dataset.rangeDay<=hi))});
document.addEventListener('pointerup',()=>{if(!rangeDragging)return;rangeDragging=false;planningEnhanced()});
document.addEventListener('dragstart',e=>{const task=e.target.closest('[data-drag-task]'),sub=e.target.closest('[data-drag-sub]');if(task)e.dataTransfer.setData('text/plain',`task:${task.dataset.dragTask}`);if(sub)e.dataTransfer.setData('text/plain',`sub:${sub.dataset.dragSub}`);e.dataTransfer.effectAllowed='move'});
document.addEventListener('dragover',e=>{const day=e.target.closest('[data-drop-day]');if(!day)return;e.preventDefault();day.classList.add('drop-target');e.dataTransfer.dropEffect='move'});
document.addEventListener('dragleave',e=>e.target.closest('[data-drop-day]')?.classList.remove('drop-target'));
document.addEventListener('drop',async e=>{const day=e.target.closest('[data-drop-day]');if(!day)return;e.preventDefault();day.classList.remove('drop-target');const [type,id]=e.dataTransfer.getData('text/plain').split(':');if(type==='task'){const task=S().data.tasks.find(x=>x.id===id);if(task)await run(()=>api.save('tasks',{...task,date:day.dataset.dropDay}),'Đã xếp Task vào '+fmtDate(day.dataset.dropDay))}if(type==='sub'){const sub=S().data.subtasks.find(x=>x.id===id);if(sub)await run(()=>api.save('subtasks',{...sub,startDate:day.dataset.dropDay,endDate:day.dataset.dropDay}),'Đã xếp Sub-task vào '+fmtDate(day.dataset.dropDay))}await refresh()});

const urgentFab=$('#floatingUrgent');
let fabDrag=null,fabMoved=false;
function clampFab(left,top){const rect=urgentFab.getBoundingClientRect(),gap=8;return {left:Math.max(gap,Math.min(left,window.innerWidth-rect.width-gap)),top:Math.max(gap,Math.min(top,window.innerHeight-rect.height-gap))}}
function placeFab(left,top,save=false){const p=clampFab(left,top);urgentFab.style.left=`${p.left}px`;urgentFab.style.top=`${p.top}px`;urgentFab.style.right='auto';urgentFab.style.bottom='auto';if(save)localStorage.setItem('flow-v3-urgent-fab',JSON.stringify(p))}
try{const saved=JSON.parse(localStorage.getItem('flow-v3-urgent-fab'));if(Number.isFinite(saved?.left)&&Number.isFinite(saved?.top))placeFab(saved.left,saved.top)}catch{}
urgentFab.addEventListener('pointerdown',e=>{const r=urgentFab.getBoundingClientRect();fabDrag={pointerId:e.pointerId,dx:e.clientX-r.left,dy:e.clientY-r.top,startX:e.clientX,startY:e.clientY};fabMoved=false;urgentFab.setPointerCapture(e.pointerId);urgentFab.classList.add('dragging');e.preventDefault()});
urgentFab.addEventListener('pointermove',e=>{if(!fabDrag||e.pointerId!==fabDrag.pointerId)return;if(Math.hypot(e.clientX-fabDrag.startX,e.clientY-fabDrag.startY)>5)fabMoved=true;placeFab(e.clientX-fabDrag.dx,e.clientY-fabDrag.dy)});
urgentFab.addEventListener('pointerup',e=>{if(!fabDrag||e.pointerId!==fabDrag.pointerId)return;urgentFab.releasePointerCapture?.(e.pointerId);urgentFab.classList.remove('dragging');const r=urgentFab.getBoundingClientRect();placeFab(r.left,r.top,true);fabDrag=null;if(!fabMoved)urgentForm()});
urgentFab.addEventListener('pointercancel',()=>{fabDrag=null;urgentFab.classList.remove('dragging')});
urgentFab.addEventListener('click',e=>e.preventDefault());
window.addEventListener('resize',()=>{if(urgentFab.style.left){const r=urgentFab.getBoundingClientRect();placeFab(r.left,r.top)}});
