// Dependency-free OOXML workbook, ZIP STORE encoding. All user text is inlineStr,
// so values beginning with =, +, -, @ cannot become spreadsheet formulas.
import {download,today} from './utils.js?v=20260928';
const xml = value => String(value??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const encoder=new TextEncoder();
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
function zip(files){const parts=[],directory=[];let offset=0;const header=(size)=>{const bytes=new Uint8Array(size);return {bytes,view:new DataView(bytes.buffer)}};for(const [name,text] of files){const filename=encoder.encode(name),data=encoder.encode(text),crc=crc32(data),local=header(30);local.view.setUint32(0,0x04034b50,true);local.view.setUint16(4,20,true);local.view.setUint32(14,crc,true);local.view.setUint32(18,data.length,true);local.view.setUint32(22,data.length,true);local.view.setUint16(26,filename.length,true);parts.push(local.bytes,filename,data);const central=header(46);central.view.setUint32(0,0x02014b50,true);central.view.setUint16(4,20,true);central.view.setUint16(6,20,true);central.view.setUint32(16,crc,true);central.view.setUint32(20,data.length,true);central.view.setUint32(24,data.length,true);central.view.setUint16(28,filename.length,true);central.view.setUint32(42,offset,true);directory.push(central.bytes,filename);offset+=30+filename.length+data.length}const length=directory.reduce((s,x)=>s+x.length,0),end=header(22);end.view.setUint32(0,0x06054b50,true);end.view.setUint16(8,files.length,true);end.view.setUint16(10,files.length,true);end.view.setUint32(12,length,true);end.view.setUint32(16,offset,true);parts.push(...directory,end.bytes);const result=new Uint8Array(offset+length+22);let pos=0;for(const p of parts){result.set(p,pos);pos+=p.length}return result}
const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';
export function workbookBytes(sheets){const files=[['[Content_Types].xml',`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`],['_rels/.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],['xl/workbook.xml',`<workbook xmlns="${ns}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map(([name],i)=>`<sheet name="${xml(name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`],['xl/_rels/workbook.xml.rels',`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}</Relationships>`]];sheets.forEach(([,rows],i)=>files.push([`xl/worksheets/sheet${i+1}.xml`,`<worksheet xmlns="${ns}"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetData>${rows.map((row,r)=>`<row r="${r+1}">${row.map(value=>typeof value==='number'&&Number.isFinite(value)?`<c t="n"><v>${value}</v></c>`:`<c t="inlineStr"><is><t xml:space="preserve">${xml(value)}</t></is></c>`).join('')}</row>`).join('')}</sheetData></worksheet>`]));return zip(files)}
export function exportSheets(data){const d={months:[],kpis:[],subtasks:[],tasks:[],urgentTasks:[],notes:[],timeEntries:[],payrolls:[],attendanceEvents:[],...data},month=id=>{const m=d.months.find(x=>x.id===id);return m?`${m.year}-${String(m.month).padStart(2,'0')}`:''},kpi=id=>d.kpis.find(x=>x.id===id),sub=id=>d.subtasks.find(x=>x.id===id),status=x=>x.completed?'Hoàn thành':'Chưa hoàn thành';return [
 ['KPI',[['Tháng','KPI','Ghi chú'],...d.kpis.map(k=>[month(k.monthId),k.name,k.note])]],
 ['Sub-task',[['Tháng','KPI','Sub-task','Trạng thái','Từ ngày','Đến ngày'],...d.subtasks.map(s=>{const children=d.tasks.filter(t=>t.subtaskId===s.id);return [month(kpi(s.kpiId)?.monthId),kpi(s.kpiId)?.name,s.name,status({completed:children.length?children.every(t=>t.completed):s.completed}),s.startDate,s.endDate]})]],
 ['Task',[['Tháng','KPI','Sub-task','Task','Trạng thái','Ngày','Từ giờ','Đến giờ','Ghi chú'],...d.tasks.map(t=>[month(kpi(sub(t.subtaskId)?.kpiId)?.monthId),kpi(sub(t.subtaskId)?.kpiId)?.name,sub(t.subtaskId)?.name,t.name,status(t),t.date,t.startTime,t.endTime,t.note])]],
 ['Việc gấp',[['Tháng','Tên','Trạng thái','Ngày','Ghi chú'],...d.urgentTasks.map(t=>[month(t.monthId),t.name,status(t),t.date,t.note])]],
 ['Ghi chú',[['Tháng','Tiêu đề','Nội dung'],...d.notes.map(n=>[month(n.monthId),n.title,n.body])]],
 ['Chấm công',[['Ngày','Check-in (giờ VN)','Check-out (giờ VN)','Tự checkout','Lý do'],...d.timeEntries.map(t=>[t.date,vnTime(t.checkInAt),vnTime(t.checkOutAt),t.autoCheckout?'Có':'Không',t.reason])]],
 ['Đơn chấm công',[['Tháng','Loại','Từ ngày','Đến ngày','Từ giờ','Đến giờ','Trạng thái','Lý do','Ngày duyệt'],...d.attendanceEvents.map(e=>[month(e.monthId),({leave:'Nghỉ phép',unpaid_leave:'Nghỉ không lương',late:'Đi trễ',early_leave:'Về sớm',early_arrival:'Đi sớm',late_departure:'Về trễ',business_trip:'Công tác',other:'Khác'})[e.type]||e.type,e.startDate,e.endDate,e.startTime,e.endTime,({draft:'Nháp',pending:'Chờ duyệt',approved:'Đã duyệt',rejected:'Từ chối'})[e.approvalStatus],e.note,vnTime(e.reviewedAt)])]],
 ['Bảng lương',[['Tháng','Lương cơ bản','Thưởng KPI','Điều chỉnh khác','Điều chỉnh chấm công','Tổng','Ghi chú'],...d.payrolls.map(p=>[month(p.monthId),Number(p.baseSalary),Number(p.kpiBonus),Number(p.otherAdjustment),Number(p.attendanceAdjustment),[p.baseSalary,p.kpiBonus,p.otherAdjustment,p.attendanceAdjustment].reduce((s,x)=>s+Number(x||0),0),p.note])]],
 ['Chi tiết lương',[['Tháng','Loại','Tên khoản','Số tiền'],...d.payrolls.flatMap(p=>(p.adjustmentItems||[]).map(i=>[month(p.monthId),i.type==='penalty'?'Phạt':'Thu nhập',i.title,Number(i.amount)]))]]
 ]}
const vnTime=value=>value?new Date(value).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):'';
export function exportWorkbook(data){download(workbookBytes(exportSheets(data)),`flow-kpi-${today()}.xlsx`,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')}
